### ISSUE TITLE
Use of undeclared type 'HTML'

### ISSUE THREAD

**Issue by russellyeo** [mattt/CommonMarkAttributedString#5]
After starting a fresh iOS Xcode project and importing `v0.1.0` via SPM, when I try to build the project I get a compiler error in `CommonMarkAttributedString/CommonMark+Extensions.swift:40`

"Use of undeclared type 'HTML'"

**Comment by mattt** [comment]
Sorry about that, @rus64. The underlying CommonMark dependency was unintentionally specified with `.from` (`> 0.2.0`) rather than `.upToNextMinor` (`~> 0.2.0`).

This is now fixed in CommonMarkAttributedString 0.1.1. The subsequent 0.2.0 release uses the most recent release of CommonMark and includes a bug fix (#1).

**Comment by russellyeo** [comment]
Great, thanks for the quick response and action!
